### ISSUE TITLE
New sounds: human/alien chatter

### ISSUE THREAD

**Issue by iamwontolla** [UnvanquishedAssets/res-legacy_src.dpkdir#3]
Offering these for consideration, under a CC-BY license.
[sound-feedback.zip](https://github.com/UnvanquishedAssets/res-legacy_src.dpkdir/files/5287714/sound-feedback.zip)

**Comment by illwieckz** [comment]
Hi @iamwontolla, that sounds good for a start!

Two remarks:

- I noticed that on poor quality sound system the submitted alien sound sounds more electronic than organic. What if the pitch lowers itself a bit on the ending? Maybe this way it would sound a bit more like it was not generated by a machine but a living thing?
- For the human sound, what if there is a bit of a human voice in the background of what you've done? Basically what you've done looks good, it is good enough to replace the current one, but maybe there is a way to add a very subtle vowel to suggest there was a people talking on the radio.

I like what you do!

[Edit: for the human sound, maybe the suggested vowel can use a lower pitch than the shhhh effect, a bit like a deep male voice]

**Comment by iamwontolla** [comment]
Took your suggestions into consideration, and they both definitely help!
[sound-feedback.zip](https://github.com/UnvanquishedAssets/res-legacy_src.dpkdir/files/5288887/sound-feedback.zip)

**Comment by illwieckz** [comment]
Woaw, I think the alien sound is good enough to be shipped now!

I'm not sure to hear a difference with your previous human sound. Well, I can hear a difference only because I know there is one and I'm looking for it, can you make the change less subtle?

**Comment by iamwontolla** [comment]
Same, I was just about to upload a better version.
[human_talk (more obvious).zip](https://github.com/UnvanquishedAssets/res-legacy_src.dpkdir/files/5288895/human_talk.more.obvious.zip)

**Comment by illwieckz** [comment]
That sound good enough! I'm going to merge them. :slightly_smiling_face:

**Comment by illwieckz** [comment]
@iamwontolla what is the name you want to be credited with?

**Comment by iamwontolla** [comment]
"Wontolla" is preferred, I could use my real name if that's the standard

**Comment by illwieckz** [comment]
Not everyone put their real name, but when they do we credit both (like `Thomas “illwieckz” Debesse`), so it's up to you. =)

**Comment by iamwontolla** [comment]
"Wontolla" is fine, then.

**Comment by illwieckz** [comment]
So, it's done:

- old files removed from there: https://github.com/UnvanquishedAssets/res-legacy_src.dpkdir/commit/cef6e55e7330014247f0692011cda1655823dcb5
- new files added there: https://github.com/UnvanquishedAssets/res-voices_src.dpkdir/commit/bd2bf19baf75e8b890d0ddcd641e1c153cbf81dd

Please make a new ticket for your next shipping. :slightly_smiling_face:

**Comment by illwieckz** [comment]
Congratulation @iamwontolla, you contributed to Unvanquished! :partying_face:
